
sudo : require
services:
  - docker 
  
before install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev ./client

script:
  - docker run react-test npm test -- --coverage

after-success:
  - docker build -t multi-client ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t milti-server ./server
  - docker build -t multi-worker ./worker